apiVersion: apps/v1
kind: Deployment
metadata:
  name: spool
spec:
  replicas: 2
  selector:
    matchLabels:
      app: spool
  template:
    metadata:
      labels:
        app: spool
    spec:
      containers:
      - name: spool
        image: iankts/spool-api:{{TAG}}
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 3000
        env:
        - name: ENV
          valueFrom:
            secretKeyRef:
              name: spool-secrets
              key: ENV
        - name: PORT
          valueFrom:
            secretKeyRef:
              name: spool-secrets
              key: PORT
---
apiVersion: v1
kind: Service
metadata:
  name: spool
spec:
  selector:
    app: spool
  ports:
  - port: 80
    targetPort: 3000
  type: LoadBalancer
