apiVersion: v1
kind: Secret
metadata:
  name: spool-secrets
type: Opaque
data:
#database secrets
  DB_NAME: __DB_NAME__
  DB_PASSWORD: __DB_PASSWORD__
  DB_USERNAME: __DB_USERNAME__
  DB_HOST: __DB_HOST__ #Aqui basta o nome do service, já que estão todos no k8s
  DB_PORT: __DB_PORT__
  DATABASE_URL: __DATABASE_URL__

#api secrets
  ENV: __ENV__
  PORT: __PORT__
