pipeline {
    agent any

    stages {

        stage ('Build Docker Image') {
            steps {
                script {
                    dockerapp = docker.build("iankts/spool-api:${env.BUILD_ID}", "-f ./Dockerfile .")
                }
            }
        }

        stage ('Push Docker Image') {
            steps {
                script {
                    docker.withRegistry('https://registry.hub.docker.com', 'dockerhub') {
                        dockerapp.push('latest')
                        dockerapp.push("${env.BUILD_ID}")
                    }
                }
            }
        }

        stage ('Deploy Kubernetes') {

            environment {
                tag_version = "${env.BUILD_ID}"
                dbName = credentials("DB_NAME")
                dbPassword = credentials("DB_PASSWORD")
                dbUsername = credentials("DB_USERNAME")
                dbHost = credentials("DB_HOST")
                dbPort = credentials("DB_PORT")
                appEnv = credentials("APP_ENV")
                appPort = credentials("APP_PORT")
            }

            steps {
                script { // Secrets deployment

                    withKubeConfig([credentialsId: 'kubeconfig']) {
                        sh 'sed -i "s/__DB_NAME__/$dbName/g" ./k8s/secrets.yaml'
                        sh 'sed -i "s/__DB_PASSWORD__/$dbPassword/g" ./k8s/secrets.yaml'
                        sh 'sed -i "s/__DB_USERNAME__/$dbUsername/g" ./k8s/secrets.yaml'
                        sh 'sed -i "s/__DB_HOST__/$dbHost/g" ./k8s/secrets.yaml'
                        sh 'sed -i "s/__DB_PORT__/$dbPort/g" ./k8s/secrets.yaml'
                        sh 'sed -i "s/__ENV__/$appEnv/g" ./k8s/secrets.yaml'
                        sh 'sed -i "s/__PORT__/$appPort/g" ./k8s/secrets.yaml'
                        sh 'kubectl apply -f ./k8s/secrets.yaml'
                    }
                }

                script { // database deployment
                    withKubeConfig([credentialsId: 'kubeconfig']) {
                        sh 'kubectl apply -f ./k8s/deployment-database.yaml'
                    }
                }

                script { // api deployment
                    withKubeConfig([credentialsId: 'kubeconfig']) {
                        sh 'sed -i "s/{{TAG}}/$tag_version/g" ./k8s/deployment-api.yaml'
                        sh 'kubectl apply -f ./k8s/deployment-api.yaml'
                    }
                }
            }

        }

    }
}